# ~/.bashrc: executed by bash(1) for non-login shells.
# Typically sourced by .profile for login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\
\[\033[35;40m\]\
  \u \
\[\033[00m\]\
\[\033[31;40m\]\
\h\
\[\033[00m\]\
\[\033[33;40m\]\
 \w \
\[\033[00m\]\

\[\033[00;32m\]\
\$\
\[\033[00m\] \
'
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Bash on Windows Subsytem for Linux sets umask to 0000 by default!!!
if [ "$(umask)" = "0000" ]; then
    umask 022
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Enable coloured output in less (including man)
# Bold
export LESS_TERMCAP_mb=$(tput bold; tput setaf 3)
# Blinking
export LESS_TERMCAP_md=$(tput bold; tput setaf 1)
# Underline
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 2)
# Standout
export LESS_TERMCAP_so=$(tput bold; tput setaf 0; tput setab 2)
# End Bold, Blinking and Underline
export LESS_TERMCAP_me=$(tput sgr0)
# End Standout
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
# End Underline
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/dot_files/bash/dircolors && eval "$(dircolors -b ~/dot_files/bash/dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'
if [ -f $(which nvim) ]; then
    alias vim='nvim'
fi

export PATH="$HOME/bin:$PATH"
export PATH="$HOME/install/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export XDG_CONFIG_HOME="$HOME/dot_files/XDG_CONFIG_HOME"

export LESSHISTFILE="-"
export EDITOR="vim"
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export INPUTRC="$HOME/dot_files/bash/inputrc"
export VIMINIT=":source ~/dot_files/vim/vimrc"

set -o vi

if ! [ $TMUX ]
then
    tmux -f ~/dot_files/tmux/tmux.conf attach 
fi

